JAEGER_AGENT_URL=127.0.0.1:6831

# TODO can not be used because of storage, see below
#export OCIS_TRACING_COLLECTOR=""
#export OCIS_TRACING_ENABLED=true
#export OCIS_TRACING_ENDPOINT=${JAEGER_AGENT_URL}

# TODO: storage can atm not be used with jaeger agent because TracingCollector is always used:
#if conf.TracingCollector == "" {
#     conf.TracingCollector = "http://localhost:14268/api/traces"
#}
#export STORAGE_TRACING_ENABLED=true
#export STORAGE_TRACING_ENDPOINT=${JAEGER_AGENT_URL}

export ACCOUNTS_TRACING_ENABLED=true
export ACCOUNTS_TRACING_ENDPOINT=${JAEGER_AGENT_URL}
export GLAUTH_TRACING_ENABLED=true
export GLAUTH_TRACING_ENDPOINT=${JAEGER_AGENT_URL}
export KONNECTD_TRACING_ENABLED=true
export KONNECTD_TRACING_ENDPOINT=${JAEGER_AGENT_URL}
export OCS_TRACING_ENABLED=true
export OCS_TRACING_ENDPOINT=${JAEGER_AGENT_URL}
export ONLYOFFICE_TRACING_ENABLED=true
export ONLYOFFICE_TRACING_ENDPOINT=${JAEGER_AGENT_URL}
export PROXY_TRACING_ENABLED=true
export PROXY_TRACING_ENDPOINT=${JAEGER_AGENT_URL}
export SETTINGS_TRACING_ENABLED=true
export SETTINGS_TRACING_ENDPOINT=${JAEGER_AGENT_URL}
export STORE_TRACING_ENABLED=true
export STORE_TRACING_ENDPOINT=${JAEGER_AGENT_URL}
export THUMBNAILS_TRACING_ENABLED=true
export THUMBNAILS_TRACING_ENDPOINT=${JAEGER_AGENT_URL}
export WEB_TRACING_ENABLED=true
export WEB_TRACING_ENDPOINT=${JAEGER_AGENT_URL}
export WEBDAV_TRACING_ENABLED=true
export WEBDAV_TRACING_ENDPOINT=${JAEGER_AGENT_URL}
